### ISSUE TITLE
Ignore Dependabot hypothesis patch updates

### ISSUE THREAD

**Issue by josh** [josh/wikidatabots#394]
```yaml
ignore:
 - dependency-name: "hypothesis"
   update-types: ["version-update:semver-patch"]
```
